pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pull code from GitHub
                git 'https://github.com/YuvinD/gopher-industries-health-app.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    // Navigate to the health-app directory and run the Maven package command
                    dir('health-app') {
                        bat "mvn clean package"
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Navigate to the health-app directory and run the Maven test command
                    dir('health-app') {
                        bat "mvn test"
                    }
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the JAR file generated in the health-app/target directory
                dir('health-app') {
                    archiveArtifacts artifacts: 'target/*.jar', fingerprint: true
                }
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}
