pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Pull code from GitHub
                git 'https://github.com/YuvinD/gopher-industries-health-app.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    // Use 'bat' to run Maven package command in Windows
                    bat "mvn clean package"
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    // Use 'bat' to run Maven test command in Windows
                    bat "mvn test"
                }
            }
        }

        stage('Archive Artifacts') {
            steps {
                // Archive the built JAR file
                archiveArtifacts artifacts: 'health-app/target/*.jar', fingerprint: true
            }
        }
    }

    post {
        success {
            echo 'Build completed successfully!'
        }
        failure {
            echo 'Build failed.'
        }
    }
}

